[versions]
# Kotlin
kotlin = "1.9.24"

# Minecraft
paper = "1.20.6-R0.1-SNAPSHOT"
paperweight = "1.7.1"
adventure = "4.17.0"

# Plugins
headdatabaseapi = "1.3.1"
placeholderapi = "2.11.5"
itemsadder = "3.6.3-beta-14"
oraxen = "1.171.0"

# Core
annotations = "24.1.0"
jalu = "1.4.1"
yaml = "1.8.4"

shadowJar = "8.1.7"

[plugins]
shadow = { id = "io.github.goooler.shadow", version.ref = "shadowJar" }

[libraries]
# Kyori
adventureMiniMessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
adventureApi = { module = "net.kyori:adventure-api", version.ref = "adventure" }

# Paper
papermc = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

headdatabaseapi = { module = "com.arcaniax:HeadDatabase-API", version.ref = "headdatabaseapi" }
placeholderapi = { module = "com.github.LoneDev6:api-itemsadder", version.ref = "itemsadder" }
itemsadder = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
oraxen = { module = "io.th0rgal:oraxen", version.ref = "oraxen" }

# Core
yaml = { module = "com.github.Carleslc.Simple-YAML:Simple-Yaml", version.ref = "yaml" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
configme = { module = "ch.jalu:configme", version.ref = "jalu" }

# Kotlin
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]
plugins = [ "headdatabaseapi", "placeholderapi", "itemsadder", "oraxen" ]
adventure = ["adventureApi", "adventureMiniMessage"]